version: '3.7'
services:
  wordpress:
    build: .
    container_name: wp-app4-demo
    restart: unless-stopped
    ports:
      - 9004:80
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-mysql}
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      VIRTUAL_HOST: app4.example.com
      VIRTUAL_PORT: 9004
    network_mode: bridge
    external_links:
      - mysql
